update parent_textedit and fix index out of range
when codes and categories changes edited deleted merges, show the change in the main window text edit.
Fixed error for index out of range: 
1 add a category
2 name it
3 rename it and press enter to apply renaming
4 results in:
Traceback (most recent call last):
File "/usr/share/QualCoder/code_text.py", line 347, in tree_menu
self.rename_category_or_code(selected)
File "/usr/share/QualCoder/code_text.py", line 675, in rename_category_or_code
+ self.codes[found]['name'] + " to: " + new_name)
IndexError: list index out of range